version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: alienregapp:latest
    container_name: web
    expose:
      - "8080"
    depends_on:
      - db
  nginx:
    image: nginx:1.17.2
    container_name: nginx
    ports:
      - "5050:5050"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  db:
    image: postgres:latest
    restart: always
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=alienregappdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jhHDF6#@H&@#H!!2
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local